# Basic Information 
title: Miaoran Zhang
title_zh: 张妙然
position: Ph.D. candidate
affiliation: Saarland University, Saarland Informatics Campus
affiliation_link: https://saarland-informatics-campus.de/en/
affiliation_logo: ./assets/img/sic.png
email: mzhang(at)lsv.uni-saarland.de
email2: miaoranzhang(at)gmail.com

# Search Engine Optimization (SEO)
keywords: miaoran zhang, zhang miaoran, miaoranzhang, zhangmiaoran

# The option is used to enable the Johns Hopkins template.
#enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=_FuKQZoAAAAJ
github_link: https://github.com/mrzhang11
linkedin: https://www.linkedin.com/in/miaoran-zhang-07923394
twitter: https://x.com/miaoranz

# Images 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/icon.png
favicon_dark: ./assets/img/icon.png

# Footnotes
footnote: website's source code from Yaoyao Liu.
footnote_link: https://github.com/yaoyao-liu/yaoyao-liu.github.io

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
